import { jitter, clamp, hoursAgo } from "../data/noise";

export function generateFleet() {
  return [
    {
      server: { id: "fleet-1", name: "Backup NAS", url: "http://192.168.1.50:8060", enabled: true },
      online: true,
      last_poll: new Date(Date.now() - 15000).toISOString(),
      hostname: "synology-nas",
      platform: "synology",
      version: "0.7.0",
      uptime: "142d 8h",
      overall_health: "healthy",
      critical_count: 0,
      warning_count: 1,
      info_count: 3,
      cpu_usage: Math.round(clamp(jitter(12, 25, 7011), 3, 40)),
      mem_percent: Math.round(clamp(jitter(58, 10, 7012), 30, 80)),
      disk_count: 4,
      container_count: 5,
      signature_valid: true,
    },
    {
      server: { id: "fleet-2", name: "Media Server", url: "http://192.168.1.51:8060", enabled: true },
      online: true,
      last_poll: new Date(Date.now() - 10000).toISOString(),
      hostname: "plex-tower",
      platform: "unraid",
      version: "0.7.0",
      uptime: "30d 14h",
      overall_health: "warning",
      critical_count: 0,
      warning_count: 4,
      info_count: 2,
      cpu_usage: Math.round(clamp(jitter(24, 20, 7001), 5, 60)),
      mem_percent: Math.round(clamp(jitter(72, 8, 7002), 40, 90)),
      disk_count: 6,
      container_count: 11,
      signature_valid: true,
    },
    {
      server: { id: "fleet-3", name: "Proxmox Node 1", url: "http://10.0.0.10:8060", enabled: true },
      online: true,
      last_poll: new Date(Date.now() - 12000).toISOString(),
      hostname: "pve-node01",
      platform: "proxmox",
      version: "0.7.0",
      uptime: "45d 9h",
      overall_health: "warning",
      critical_count: 0,
      warning_count: 2,
      info_count: 3,
      cpu_usage: Math.round(clamp(jitter(35, 18, 7021), 8, 70)),
      mem_percent: Math.round(clamp(jitter(48, 12, 7022), 20, 75)),
      disk_count: 4,
      container_count: 3,
      signature_valid: true,
    },
    {
      server: { id: "fleet-4", name: "Remote Backup", url: "http://192.168.50.10:8060", enabled: true },
      online: false,
      last_poll: hoursAgo(48),
      hostname: "",
      platform: "",
      version: "",
      uptime: "",
      overall_health: "unknown",
      critical_count: 0,
      warning_count: 0,
      info_count: 0,
      cpu_usage: 0,
      mem_percent: 0,
      disk_count: 0,
      container_count: 0,
      signature_valid: false,
    },
  ];
}
