import { jitter, clamp, hoursAgo } from "../data/noise";

export function generateFleet() {
  return [
    {
      name: "Primary NAS",
      url: "http://10.0.1.50:8080",
      status: "online",
      hostname: "unraid-tower",
      platform: "Unraid 7.0.1",
      version: "0.7.0",
      last_seen: hoursAgo(0.01),
      uptime: "30d 14h",
      critical_count: 1,
      warning_count: 3,
      info_count: 2,
      overall_health: "warning",
      cpu_usage: Math.round(clamp(jitter(24, 20, 7001), 5, 60)),
      mem_percent: Math.round(clamp(jitter(72, 8, 7002), 40, 90)),
      disk_count: 6,
      container_count: 11,
      signature_valid: true,
    },
    {
      name: "Synology Backup",
      url: "http://10.0.1.60:8080",
      status: "online",
      hostname: "synology-nas",
      platform: "Synology DSM 7.2.2",
      version: "0.7.0",
      last_seen: hoursAgo(0.02),
      uptime: "90d 6h",
      critical_count: 0,
      warning_count: 1,
      info_count: 1,
      overall_health: "healthy",
      cpu_usage: Math.round(clamp(jitter(12, 25, 7011), 3, 40)),
      mem_percent: Math.round(clamp(jitter(58, 10, 7012), 30, 80)),
      disk_count: 4,
      container_count: 5,
      signature_valid: true,
    },
    {
      name: "Proxmox Host",
      url: "http://10.0.1.70:8080",
      status: "online",
      hostname: "pve-node01",
      platform: "Proxmox VE 8.3.2",
      version: "0.7.0",
      last_seen: hoursAgo(0.01),
      uptime: "45d 9h",
      critical_count: 0,
      warning_count: 2,
      info_count: 3,
      overall_health: "warning",
      cpu_usage: Math.round(clamp(jitter(35, 18, 7021), 8, 70)),
      mem_percent: Math.round(clamp(jitter(48, 12, 7022), 20, 75)),
      disk_count: 4,
      container_count: 3,
      signature_valid: true,
    },
    {
      name: "Remote Backup",
      url: "http://192.168.50.10:8080",
      status: "offline",
      hostname: "offsite-nas",
      platform: "Unknown",
      version: "",
      last_seen: hoursAgo(48),
      uptime: "",
      critical_count: 0,
      warning_count: 0,
      info_count: 0,
      overall_health: "unknown",
      cpu_usage: 0,
      mem_percent: 0,
      disk_count: 0,
      container_count: 0,
      signature_valid: false,
    },
  ];
}
